export const STORE_ITEM = 'STORE_ITEM';
export const STORE_GALLERY_ITEM = 'STORE_GALLERY_ITEM';
export const CREATE_GALLERY_ITEM = 'CREATE_GALLERY_ITEM';
export const STORE_TEXT = 'STORE_TEXT';
export const CHANGE_GALLERY_INDEX = 'CHANGE_GALLERY_INDEX';
export const CHANGE_ITEM_INDEX = 'CHANGE_ITEM_INDEX';
export const EDIT_ITEMS = 'EDIT_ITEMS';
export const SET_LAST_GALLERY = 'EDIT_ITEMS';